const SCALE_FACTOR = 1;
const LOGICAL_WIDTH = 640;
const LOGICAL_HEIGHT = 360;
const VIEWPORT_WIDTH = 1280;
const VIEWPORT_HEIGHT = 720;

export { SCALE_FACTOR, LOGICAL_WIDTH, LOGICAL_HEIGHT, VIEWPORT_WIDTH, VIEWPORT_HEIGHT };
